spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: false
        generate_statistics: false

logging:
  level:
    root: INFO
    com.pulse: INFO
    com.pulse.config.AwsSecretsConfig: DEBUG
    software.amazon.awssdk: DEBUG
  file:
    name: /home/ec2-user/pulse/logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: native
  tomcat:
    # noinspection SpellCheckingInspection
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto

seoul-api:
  page-size: 1000
  services:
    bus: CardBusTimeNew
    subway: CardSubwayTime